name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Chạy mỗi ngày vào lúc 00:00 UTC
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "## Profile Update" > README.md
          echo "Last updated: $(date)" >> README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Automated update of README.md"
          git push